import type { Metadata } from "next";
import { Outfit, Inter } from "next/font/google";
import Script from "next/script";
import AggressiveAds from "@/components/AggressiveAds";
import ConditionalAdScript from "@/components/ConditionalAdScript";
import { ThemeProvider } from "@/components/theme/theme-provider";
import "./globals.css";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ConditionalAdScript />
      </head>
      <body
        className={`${outfit.variable} ${inter.variable} antialiased font-inter`}
      >
        <ThemeProvider defaultTheme="zed">
          <AggressiveAds />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
